[openai]
api_key = "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"  # Replace with your real key
